---
output:
  pdf_document: default
  html_document: default
---
\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
setwd("/home/guest/Whisler_ENV872_EDA_FinalProject")

# Load your packages
library(tidyverse)
library(lubridate)
library(trend)
library(zoo)
library(Kendall)
library(tseries)

# Set your ggplot theme
mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

# Load your datasets
read.csv("~/Whisler_ENV872_EDA_FinalProject/Data/Processed/clean_data.csv")

```


# Rationale and Research Questions

As temperatures continue to destabilize across the globe in response to greenhouse gas emissions, certain areas have been 
subjected to weather phenomena of increased duration and intensity. Among these regions unfortunate enough to be facing the brunt of climate change is the state of California on the western coast of the United States. According to the California Coastal Commission, "climate change is expected to continue shifting and intensifying weather patterns around the globe. In California, events such as El Niño and extended drought are of particular concern." As a result, shifts in water temperature are also likely to occur, which can have devastating impacts on coastal ecosystems.

This project examines empirical temperature and precipitation data from the year 2022 and seeks to analyze fluctuations in water temperature over the duration of the year, as well as determine if there is a correlation between water temperature and extreme weather events that cause dramatic increases in precipitation.




\newpage

# Dataset Information

Data for this project was sourced from two online repositories. 

For water temperature, data was taken from the National Data Buoy Center's website as part of the National Oceanic and Atmospheric Administration (NOAA); in particular, the buoy located at Station 46092 at coordinates 36.751 N, 122.029 W in Monterey Bay was used to provide data points several times per day for water temperature. This data also included information that was not pertinent to these research questions, such as dew point and wave direction, which were excluded from the refined dataset that was used for this analysis. Data was collected from quality controlled datasets for standard meteorological data for this buoy from NOAA's website.

For precipitation, Weather Underground, a subsidiary of The Weather Company, was used due to its accuracy and storage of long-term meteorological records. Data was found on the Monterey Peninsula Airport Station's page of the Weather Underground website and precipitation records were manually transcribed into Microsoft Excel and subsequently exported as a comma-separated value (.csv) file for use in R's coding language.


\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References

State of California - Ca. Coastal Commission. (n.d.). California Coastal Commission. ca. https://www.coastal.ca.gov/climate/extreme-weather/ 
